# syntax = docker/dockerfile:experimental@sha256:3c244c0c6fc9d6aa3ddb73af4264b3a23597523ac553294218c13735a2c6cf79
# 20.04
FROM ubuntu:focal-20241011

ARG SKAFFOLD_MODE
ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt update && apt install -y build-essential valgrind

# Rest of the files
COPY . ./
RUN make
